# Generated by Django 5.0.2 on 2024-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.JSONField(default=list)),
                ('scrolls', models.JSONField(default=list)),
                ('time_spent', models.IntegerField(default=0)),
            ],
        ),
    ]
